In [ ]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

## Train Data Analysis

In [ ]:
train_set=pd.read_csv('/content/train_dataset.csv')

In [ ]:
train_set.head(10)

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  7135    1654     CL  D-penicillamine  19581   F       N            N   
1  7326      41      C  D-penicillamine  22880   F     NaN            N   
2  7254     297      D              NaN  27957   F       N            N   
3  3135    1872      C  D-penicillamine  21111   F     NaN            Y   
4  2483     939     CL  D-penicillamine  18061   F     NaN          NaN   
5  2306    1255      C          Placebo  14353   F       Y            N   
6  2525    2065      C              NaN  25357   F       N            Y   
7  6908    1118      D          Placebo  28620   F     NaN          NaN   
8  8388    4313      D              NaN  24638   F       N            N   
9  9132    3240      D              NaN  13860   F       N            N   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       Y     N        0.3        279.0     2.96    84.0    1500.8   99.43   
1     NaN     N        0.3          NaN     2.96     NaN    1835.4   26.35   
2     NaN     N        0.3        328.0     2.64     4.0       NaN     NaN   
3       Y     N        0.3        302.0     2.02    49.0       NaN   26.35   
4     NaN     N        0.5        344.0     3.11    91.0       NaN  104.56   
5       N     N        9.9          NaN     3.57     4.0     462.6  103.40   
6     NaN     N        0.3          NaN     2.60   103.0       NaN     NaN   
7       N     N        2.0        357.0     3.11    94.0    3403.8     NaN   
8     NaN     N        1.2          NaN     3.51    67.0    1850.6   44.21   
9     NaN     N        8.7          NaN     3.02     NaN       NaN   87.62   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            NaN        NaN         10.5      4  
4            NaN      306.0         11.4      2  
5          126.0      276.0         12.1      4  
6          200.0      365.0         10.5      4  
7            NaN      254.0         10.1      4  
8            NaN      434.0         11.1      2  
9            NaN      102.0         11.2      3

In [ ]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6800 entries, 0 to 6799
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             6800 non-null   int64  
 1   N_Days         6800 non-null   int64  
 2   Status         6800 non-null   object 
 3   Drug           4775 non-null   object 
 4   Age            6800 non-null   int64  
 5   Sex            6800 non-null   object 
 6   Ascites        4554 non-null   object 
 7   Hepatomegaly   4373 non-null   object 
 8   Spiders        4210 non-null   object 
 9   Edema          6800 non-null   object 
 10  Bilirubin      6800 non-null   float64
 11  Cholesterol    3699 non-null   float64
 12  Albumin        6800 non-null   float64
 13  Copper         4644 non-null   float64
 14  Alk_Phos       4302 non-null   float64
 15  SGOT           4698 non-null   float64
 16  Tryglicerides  3988 non-null   float64
 17  Platelets      6462 non-null   float64
 18  Prothrom

In [ ]:
Data1=train_set

In [ ]:
Data1.isnull().sum()

ID                  0
N_Days              0
Status              0
Drug             2025
Age                 0
Sex                 0
Ascites          2246
Hepatomegaly     2427
Spiders          2590
Edema               0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [ ]:
Data1=Data1.replace(np.nan,0)

In [ ]:
Data1.head()

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  7135    1654     CL  D-penicillamine  19581   F       N            N   
1  7326      41      C  D-penicillamine  22880   F       0            N   
2  7254     297      D                0  27957   F       N            N   
3  3135    1872      C  D-penicillamine  21111   F       0            Y   
4  2483     939     CL  D-penicillamine  18061   F       0            0   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       Y     N        0.3        279.0     2.96    84.0    1500.8   99.43   
1       0     N        0.3          0.0     2.96     0.0    1835.4   26.35   
2       0     N        0.3        328.0     2.64     4.0       0.0    0.00   
3       Y     N        0.3        302.0     2.02    49.0       0.0   26.35   
4       0     N        0.5        344.0     3.11    91.0       0.0  104.56   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            0.0        0.0         10.5      4  
4            0.0      306.0         11.4      2

In [ ]:
print(Data1)

        ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0     7135    1654     CL  D-penicillamine  19581   F       N            N   
1     7326      41      C  D-penicillamine  22880   F       0            N   
2     7254     297      D                0  27957   F       N            N   
3     3135    1872      C  D-penicillamine  21111   F       0            Y   
4     2483     939     CL  D-penicillamine  18061   F       0            0   
...    ...     ...    ...              ...    ...  ..     ...          ...   
6795  4622    1762      C          Placebo  20909   M       0            N   
6796  4446    2955      C          Placebo  28650   F       Y            N   
6797  4082     584      C                0  24102   F       N            Y   
6798  2248    1426     CL  D-penicillamine  19791   F       N            0   
6799  4826     125      D  D-penicillamine  25245   F       Y            N   

     Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Al

In [ ]:
Data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6800 entries, 0 to 6799
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             6800 non-null   int64  
 1   N_Days         6800 non-null   int64  
 2   Status         6800 non-null   object 
 3   Drug           6800 non-null   object 
 4   Age            6800 non-null   int64  
 5   Sex            6800 non-null   object 
 6   Ascites        6800 non-null   object 
 7   Hepatomegaly   6800 non-null   object 
 8   Spiders        6800 non-null   object 
 9   Edema          6800 non-null   object 
 10  Bilirubin      6800 non-null   float64
 11  Cholesterol    6800 non-null   float64
 12  Albumin        6800 non-null   float64
 13  Copper         6800 non-null   float64
 14  Alk_Phos       6800 non-null   float64
 15  SGOT           6800 non-null   float64
 16  Tryglicerides  6800 non-null   float64
 17  Platelets      6800 non-null   float64
 18  Prothrom

In [ ]:
Data1.duplicated().sum()

0

In [ ]:
Data1.head(10)

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  7135    1654     CL  D-penicillamine  19581   F       N            N   
1  7326      41      C  D-penicillamine  22880   F       0            N   
2  7254     297      D                0  27957   F       N            N   
3  3135    1872      C  D-penicillamine  21111   F       0            Y   
4  2483     939     CL  D-penicillamine  18061   F       0            0   
5  2306    1255      C          Placebo  14353   F       Y            N   
6  2525    2065      C                0  25357   F       N            Y   
7  6908    1118      D          Placebo  28620   F       0            0   
8  8388    4313      D                0  24638   F       N            N   
9  9132    3240      D                0  13860   F       N            N   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       Y     N        0.3        279.0     2.96    84.0    1500.8   99.43   
1       0     N        0.3          0.0     2.96     0.0    1835.4   26.35   
2       0     N        0.3        328.0     2.64     4.0       0.0    0.00   
3       Y     N        0.3        302.0     2.02    49.0       0.0   26.35   
4       0     N        0.5        344.0     3.11    91.0       0.0  104.56   
5       N     N        9.9          0.0     3.57     4.0     462.6  103.40   
6       0     N        0.3          0.0     2.60   103.0       0.0    0.00   
7       N     N        2.0        357.0     3.11    94.0    3403.8    0.00   
8       0     N        1.2          0.0     3.51    67.0    1850.6   44.21   
9       0     N        8.7          0.0     3.02     0.0       0.0   87.62   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            0.0        0.0         10.5      4  
4            0.0      306.0         11.4      2  
5          126.0      276.0         12.1      4  
6          200.0      365.0         10.5      4  
7            0.0      254.0         10.1      4  
8            0.0      434.0         11.1      2  
9            0.0      102.0         11.2      3

In [ ]:
Data1['Status']=Data1['Status'].replace('C',0)
Data1['Status']=Data1['Status'].replace('CL',1)
Data1['Status']=Data1['Status'].replace('D',1)

In [ ]:
  keys=['Ascites', 'Hepatomegaly', 'Spiders', 'Edema']
  for col in keys:
    Data1[col]= Data1[col].replace('N',0)
    Data1[col]= Data1[col].replace('Y',1)


In [ ]:
Data1['Sex']=Data1['Sex'].replace('M',1)
Data1['Sex']=Data1['Sex'].replace('F',0)

In [ ]:
Data1['Drug']=Data1['Drug'].replace('D-penicillamine', 1)
Data1['Drug']=Data1['Drug'].replace('Placebo', 0)

In [ ]:
Data1['Edema'] = Data1['Edema'].replace('S', 0)

In [ ]:
Data1.head(10)

ID  N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  \
0  7135    1654       1     1  19581    0        0             0        1   
1  7326      41       0     1  22880    0        0             0        0   
2  7254     297       1     0  27957    0        0             0        0   
3  3135    1872       0     1  21111    0        0             1        1   
4  2483     939       1     1  18061    0        0             0        0   
5  2306    1255       0     0  14353    0        1             0        0   
6  2525    2065       0     0  25357    0        0             1        0   
7  6908    1118       1     0  28620    0        0             0        0   
8  8388    4313       1     0  24638    0        0             0        0   
9  9132    3240       1     0  13860    0        0             0        0   

   Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0      0        0.3        279.0     2.96    84.0    1500.8   99.43   
1      0        0.3          0.0     2.96     0.0    1835.4   26.35   
2      0        0.3        328.0     2.64     4.0       0.0    0.00   
3      0        0.3        302.0     2.02    49.0       0.0   26.35   
4      0        0.5        344.0     3.11    91.0       0.0  104.56   
5      0        9.9          0.0     3.57     4.0     462.6  103.40   
6      0        0.3          0.0     2.60   103.0       0.0    0.00   
7      0        2.0        357.0     3.11    94.0    3403.8    0.00   
8      0        1.2          0.0     3.51    67.0    1850.6   44.21   
9      0        8.7          0.0     3.02     0.0       0.0   87.62   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            0.0        0.0         10.5      4  
4            0.0      306.0         11.4      2  
5          126.0      276.0         12.1      4  
6          200.0      365.0         10.5      4  
7            0.0      254.0         10.1      4  
8            0.0      434.0         11.1      2  
9            0.0      102.0         11.2      3

In [ ]:
Data1.shape

(6800, 20)

In [ ]:
Data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6800 entries, 0 to 6799
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             6800 non-null   int64  
 1   N_Days         6800 non-null   int64  
 2   Status         6800 non-null   int64  
 3   Drug           6800 non-null   int64  
 4   Age            6800 non-null   int64  
 5   Sex            6800 non-null   int64  
 6   Ascites        6800 non-null   int64  
 7   Hepatomegaly   6800 non-null   int64  
 8   Spiders        6800 non-null   int64  
 9   Edema          6800 non-null   int64  
 10  Bilirubin      6800 non-null   float64
 11  Cholesterol    6800 non-null   float64
 12  Albumin        6800 non-null   float64
 13  Copper         6800 non-null   float64
 14  Alk_Phos       6800 non-null   float64
 15  SGOT           6800 non-null   float64
 16  Tryglicerides  6800 non-null   float64
 17  Platelets      6800 non-null   float64
 18  Prothrom

In [ ]:
X=Data1.drop(['Stage'],axis=1)
y=Data1['Stage']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2,random_state = 64)

## Using Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
predictions=rf.predict(X_test)

In [ ]:
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [ ]:
print(cm)

[[  0   2  17  69]
 [  0   9  48 215]
 [  0   6 100 169]
 [  0  12 101 612]]


In [ ]:
print(ac)

0.5301470588235294


## Using Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

Predictions_2 = classifier.predict(X_test)


In [ ]:
cm_2=confusion_matrix(y_test,Predictions_2)
ac_2=accuracy_score(y_test,Predictions_2)
print(cm_2)

[[  4  20  22  42]
 [ 20  69  49 134]
 [ 25  69  91  90]
 [ 46 161 116 402]]


In [ ]:
print(ac_2)

0.4161764705882353


# TEST DATA ANALYSIS

In [ ]:
test_set=pd.read_csv('/content/test_dataset.csv')

In [ ]:
test_set.head(10)

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  3870      41      C          Placebo  22553   F       N          NaN   
1  3462    1811      C  D-penicillamine  16223   F       N            Y   
2  1632     954      C  D-penicillamine  27100   F       N            N   
3   722    1969      D          Placebo  17039   F       N            Y   
4  1000    2721      D  D-penicillamine  17738   F     NaN          NaN   
5  2184     947      C              NaN  22296   F       N            N   
6  4800     835      D  D-penicillamine  18606   F       N          NaN   
7  2923    1949      D          Placebo  27379   F       Y            N   
8  1525    4795      C  D-penicillamine  28650   F       N            Y   
9  1995    4795      C          Placebo  20113   F     NaN          NaN   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       N     N        1.4        247.0     3.62     NaN       NaN  108.65   
1       N     N        0.3        311.0     2.80    92.0    1748.1     NaN   
2       N     N        0.4          NaN     3.56     NaN       NaN   43.52   
3       N     N        1.2          NaN     3.16     NaN     617.1  113.76   
4     NaN     N        3.2          NaN     2.36    89.0    1782.4     NaN   
5       N     N        3.0        206.0     3.61    84.0    2003.3   37.87   
6     NaN     N        2.3        120.0     3.42   162.0    1574.8  118.21   
7       N     S        1.3          NaN     3.54   330.0     963.3  109.10   
8       N     N        5.4        349.0     2.78    79.0       NaN   55.14   
9     NaN     Y        0.7        328.0     3.50   100.0    2270.1  116.91   

   Tryglicerides  Platelets  Prothrombin  
0            NaN      169.0         11.6  
1          129.0      321.0         11.5  
2            NaN      296.0         10.3  
3            NaN      125.0         10.9  
4          129.0      138.0         10.6  
5          115.0      267.0         10.6  
6          118.0      214.0         10.0  
7          129.0      297.0         11.0  
8          125.0       62.0         10.0  
9            NaN        NaN         11.2

In [ ]:
Data2=test_set

In [ ]:
Data2=Data2.replace(np.nan,0)

In [ ]:
Data2.head(10)

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  3870      41      C          Placebo  22553   F       N            0   
1  3462    1811      C  D-penicillamine  16223   F       N            Y   
2  1632     954      C  D-penicillamine  27100   F       N            N   
3   722    1969      D          Placebo  17039   F       N            Y   
4  1000    2721      D  D-penicillamine  17738   F       0            0   
5  2184     947      C                0  22296   F       N            N   
6  4800     835      D  D-penicillamine  18606   F       N            0   
7  2923    1949      D          Placebo  27379   F       Y            N   
8  1525    4795      C  D-penicillamine  28650   F       N            Y   
9  1995    4795      C          Placebo  20113   F       0            0   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       N     N        1.4        247.0     3.62     0.0       0.0  108.65   
1       N     N        0.3        311.0     2.80    92.0    1748.1    0.00   
2       N     N        0.4          0.0     3.56     0.0       0.0   43.52   
3       N     N        1.2          0.0     3.16     0.0     617.1  113.76   
4       0     N        3.2          0.0     2.36    89.0    1782.4    0.00   
5       N     N        3.0        206.0     3.61    84.0    2003.3   37.87   
6       0     N        2.3        120.0     3.42   162.0    1574.8  118.21   
7       N     S        1.3          0.0     3.54   330.0     963.3  109.10   
8       N     N        5.4        349.0     2.78    79.0       0.0   55.14   
9       0     Y        0.7        328.0     3.50   100.0    2270.1  116.91   

   Tryglicerides  Platelets  Prothrombin  
0            0.0      169.0         11.6  
1          129.0      321.0         11.5  
2            0.0      296.0         10.3  
3            0.0      125.0         10.9  
4          129.0      138.0         10.6  
5          115.0      267.0         10.6  
6          118.0      214.0         10.0  
7          129.0      297.0         11.0  
8          125.0       62.0         10.0  
9            0.0        0.0         11.2

In [ ]:
Data2.shape

(3200, 19)

In [ ]:
Data2['Status'] = Data2['Status'].replace('C', 0)
Data2['Status'] = Data2['Status'].replace('CL', 1)
Data2['Status'] = Data2['Status'].replace('D', 1)

In [ ]:
keys = ['Ascites','Hepatomegaly','Spiders','Edema']
for col in keys:
    Data2[col] = Data2[col].replace('N', 0)
    Data2[col] = Data2[col].replace('Y', 1)
    
Data2['Sex'] = Data2['Sex'].replace('M', 1)
Data2['Sex'] = Data2['Sex'].replace('F', 0)

Data2['Drug'] = Data2['Drug'].replace('D-penicillamine', 1)
Data2['Drug'] = Data2['Drug'].replace('Placebo', 0)

Data2['Edema'] = Data2['Edema'].replace('S', 0)


In [ ]:
from scipy import stats
import numpy as np
z=np.abs(stats.zscore(Data2[['Bilirubin','Alk_Phos','SGOT','Tryglicerides','Prothrombin','Copper','Albumin','Cholesterol']]))
print(z)

      Bilirubin  Alk_Phos      SGOT  Tryglicerides  Prothrombin    Copper  \
0      0.142435  0.742930  1.041146       1.057156     0.305834  0.853992   
1      0.477285  0.409163  1.076937       0.632964     0.253954  0.862856   
2      0.446844  0.742930  0.228534       1.057156     0.368610  0.853992   
3      0.203317  0.336227  1.140763       1.057156     0.057328  0.853992   
4      0.405502  0.431768  1.076937       0.632964     0.212969  0.806872   
...         ...       ...       ...            ...          ...       ...   
3195   0.477285  0.617292  1.100215       1.057156     0.057328  0.853992   
3196   0.862116  0.050044  0.443559       1.117727     0.420490  1.124115   
3197   0.325081  0.811186  1.354034       0.659167     0.305834  0.686039   
3198   4.088854  0.227659  1.130626       0.646066     0.368610  0.256827   
3199   0.477285  0.310766  1.076937       0.593659     0.109208  0.321676   

       Albumin  Cholesterol  
0     1.078546     0.529773  
1     0.458803 

In [ ]:
## Removing Outliers
Data2_new=Data2[(z<3).all(axis=1)]
print('Before removing Outlier',Data2.shape)
print('After removing Outlier',Data2_new.shape)


Before removing Outlier (3200, 19)
After removing Outlier (2880, 19)


In [ ]:
X1_train,X1_test=train_test_split(Data2_new,test_size=0.1)

In [ ]:
X1_train.shape

(2592, 19)

In [ ]:
X1_test.shape

(288, 19)

# Using Random Forest Classifier


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_predict_test_rf = rf.predict(X1_test)
print(y_predict_test_rf)

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 2 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


# Using Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)


y_predict_test_rf2 = classifier.predict(X1_test)
print(y_predict_test_rf2)

[4 4 4 4 2 2 4 4 2 4 4 2 2 4 4 2 4 1 4 4 4 4 4 4 4 2 2 2 4 4 4 4 2 4 2 4 4
 4 4 4 2 4 4 4 4 2 4 2 4 4 4 4 4 4 4 4 2 2 4 4 4 4 2 4 4 2 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 2 4 4 4 4 4 1 4 4 4 4 4 4 4 4 2 4 4 4 2 4 1 1 4 4 4 4 4 4
 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 1 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 2 4 2 4
 2 4 4 4 4 4 4 2 4 4 4 1 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 2 2 4 4 4 4 4 4 4 4 2 4 4 4 2 4 4 4
 4 4 4 2 2 2 2 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 2 4 4 4 4 2 4 4 1 4 2 4 4
 2 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 2 4 4 2]
